package constant

const (
	SHIPPING_UNIT_HASAKI              = 1
	SHIPPING_UNIT_VN_POST             = 2
	SHIPPING_UNIT_SHOPEE              = 3
	SHIPPING_UNIT_PICK_UP             = 4
	SHIPPING_UNIT_LAZADA              = 5
	SHIPPING_UNIT_GIAO_HANG_TIET_KIEM = 6
	SHIPPING_UNIT_TIKTOK              = 7
	SHIPPING_UNIT_VIETTEL             = 8
	SHIPPING_UNIT_NETCO               = 9
	SHIPPING_UNIT_GIAO_HANG_NHANH     = 10
	SHIPPING_UNIT_DHL                 = 12
	SHIPPING_UNIT_HASAKI_NOW          = 13
	SHIPPING_UNIT_AHAMOVE             = 14
	SHIPPING_UNIT_SHOPEE_EXPRESS      = 16
	SHIPPING_UNIT_NHATTIN_LOGISTICS   = 17
	SHIPPING_UNIT_EMS                 = 527
)

var SHIPPING_UNIT = map[int]string{
	SHIPPING_UNIT_HASAKI:              "HASAKI",
	SHIPPING_UNIT_VN_POST:             "VN POST",
	SHIPPING_UNIT_SHOPEE:              "SHOPEE",
	SHIPPING_UNIT_PICK_UP:             "PICK UP",
	SHIPPING_UNIT_LAZADA:              "LAZADA",
	SHIPPING_UNIT_GIAO_HANG_TIET_KIEM: "GIAO HÀNG TIẾT KIỆM",
	SHIPPING_UNIT_TIKTOK:              "TIKTOK",
	SHIPPING_UNIT_VIETTEL:             "VIETTEL",
	SHIPPING_UNIT_NETCO:               "NETCO",
	SHIPPING_UNIT_GIAO_HANG_NHANH:     "GIAO HÀNG NHANH",
	SHIPPING_UNIT_DHL:                 "DHL",
	SHIPPING_UNIT_HASAKI_NOW:          "HASAKI NOW",
	SHIPPING_UNIT_AHAMOVE:             "AHAMOVE",
	SHIPPING_UNIT_SHOPEE_EXPRESS:      "SHOPEE EXPRESS",
	SHIPPING_UNIT_NHATTIN_LOGISTICS:   "NHATTIN LOGISTICS",
	SHIPPING_UNIT_EMS:                 "EMS",
}
